version: "5.1"
services:
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    ports:
      - "9000"
    volumes:
      - ./web:/var/www/html
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
  mariadb:
    build: requirements/mariadb/.
    container_name: mysqld
    ports:
      - "3306"
    networks:
      inception:
        name: inception
