version: "5.1"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/htrindad/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/htrindad/data/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception

services:
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    ports:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
        - .env
    networks:
        - inception
    restart: always
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
        - inception
    depends_on:
        - wordpress
    restart: always
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306"
    networks:
        - inception
    env_file:
        - .env
    restart: always
